### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by JuanLPalacios** [leopiresgoss/first-capstone#9]
Great work on your design is looking great!

some things to improve:

- you could use more semantic elements for the HTML like ul dl
- you could space more the cards of the speakers

**Comment by Kakalanp** [comment]
Great work! 🎉 

Your project looks good, and the topic is really touching. 💟 

I have, actually, nothing else to add, as the project may be simple, but it works fine.

Keep up the good work! 🍀

**Comment by leopiresgoss** [comment]
Thank you. I've improved my code :slightly_smiling_face:
